/**
 * GRAVY v2.0 — exogena_data.ts
 * Autogenerated file mapping accounts and columns from FormatosBASE.xlsx.
 */

export const EXOGENA_FORMATS = [
  {
    "id": "1001",
    "name": "Format 1001 - Pagos y Retenciones Practicadas"
  },
  {
    "id": "1003",
    "name": "Format 1003 - Retenciones que le Practicaron"
  },
  {
    "id": "1004",
    "name": "Format 1004 - Descuentos Tributarios"
  },
  {
    "id": "1005",
    "name": "Format 1005 - IVA Descontable"
  },
  {
    "id": "1006",
    "name": "Format 1006 - IVA Generado"
  },
  {
    "id": "1007",
    "name": "Format 1007 - Ingresos Recibidos"
  },
  {
    "id": "1008",
    "name": "Format 1008 - Saldos de Cuentas por Cobrar"
  },
  {
    "id": "1009",
    "name": "Format 1009 - Saldos de Cuentas por Pagar"
  },
  {
    "id": "1010",
    "name": "Format 1010 - Socios, Accionistas y Aportantes"
  },
  {
    "id": "1011",
    "name": "Format 1011 - Declaraciones Tributarias / Saldos"
  },
  {
    "id": "1012",
    "name": "Format 1012 - Bancos e Inversiones"
  },
  {
    "id": "1647",
    "name": "Format 1647 - Ingresos Recibidos para Terceros"
  },
  {
    "id": "2276",
    "name": "Format 2276 - Certificado de Ingresos y Retenciones (Laboral)"
  }
];

export const EXOGENA_COLUMNS: Record<string, string[]> = {
  "1001": [
    "Concepto",
    "Tipo de documento",
    "Número identificación ",
    "Primer apellido del informado",
    "Segundo apellido del informado",
    "Primer nombre del informado",
    "Otros nombres del informado",
    "Razón social informado",
    "Dirección",
    "Código dpto",
    "Código mcp",
    "País de Residencia o domicilio",
    "Pago o abono en cuenta deducible",
    "Pago o abono en cuenta NO deducible",
    "IVA mayor valor del costo o gasto, deducible",
    "IVA mayor valor del costo o gasto no deducible",
    "Retención en la fuente practicada Renta",
    "Retención en la fuente asumida Renta",
    "Retención en la fuente practicada IVA Régimen común",
    "Retención en la fuente practicada IVA no domiciliados"
  ],
  "1003": [
    "Concepto",
    "Tipo de documento",
    "Número identificación del informado",
    "DV",
    "Primer apellido del informado",
    "Segundo apellido del informado",
    "Primer nombre del informado",
    "Otros nombres del informado",
    "Razón social informado",
    "Dirección",
    "Código del Departamento",
    "Código del Municipio",
    "Valor acumulado del pago o abono sujeto a Retención en la fuente",
    "Retención que le practicaron"
  ],
  "1004": [
    "Concepto",
    "Tipo de documento del Tercero",
    "Número de Identificación del Tercero",
    "Primer apellido",
    "Segundo apellido ",
    "Primer nombre",
    "Otros nombres",
    "Razón Social",
    "Dirección",
    "Código dpto",
    "Código mcp",
    "Código País",
    "Correo Electrónico",
    "Valor del Pago o Abono en Cuenta",
    "Valor del Descuento Tributario"
  ],
  "1005": [
    "Tipo de documento",
    "Número identificación",
    "DV",
    "Primer apellido del informado",
    "Segundo apellido del informado",
    "Primer nombre del informado",
    "Otros nombres del informado",
    "Razón social informado",
    "Impuesto Descontable",
    "IVA resultante por devoluciones en ventas anuladas. rescindidas o resueltas"
  ],
  "1006": [
    "Tipo de Documento",
    "Número identificación",
    "DV",
    "Primer apellido del informado",
    "Segundo apellido del informado",
    "Primer nombre del informado",
    "Otros nombres del informado",
    "Razón social informado",
    "Impuesto generado",
    "IVA recuperado en devoluciones en compras anuladas. rescindidas o resueltas",
    "Impuesto al consumo"
  ],
  "1007": [
    "Concepto",
    "Tipo de documento",
    "Número identificación ",
    "Primer apellido del informado",
    "Segundo apellido del informado",
    "Primer nombre del informado",
    "Otros nombres del informado",
    "Razón social informado",
    "País de Residencia o domicilio",
    "Ingresos brutos recibidos",
    "Devoluciones,  rebajas y descuentos"
  ],
  "1008": [
    "Concepto",
    "Tipo de documento",
    "Número identificación deudor",
    "DV",
    "Primer apellido deudor",
    "Segundo apellido deudor",
    "Primer nombre deudor",
    "Otros nombres deudor",
    "Razón social deudor",
    "Dirección",
    "Código dpto",
    "Código mcp",
    "País de Residencia o domicilio",
    "Saldo cuentas por cobrar al 31-12"
  ],
  "1009": [
    "Concepto",
    "Tipo de documento",
    "Número identificación acreedor",
    "DV",
    "Primer apellido acreedor",
    "Segundo apellido acreedor",
    "Primer nombre acreedor",
    "Otros nombres acreedor",
    "Razón social acreedor",
    "Dirección",
    "Código dpto",
    "Código mcp",
    "País de Residencia o domicilio",
    "Saldo cuentas por pagar al 31-12"
  ],
  "1010": [
    "Tipo de documento",
    "Número identificación socio o accionista",
    "DV",
    "Primer apellido socio o accionista",
    "Segundo apellido socio o accionista",
    "Primer nombre del socio o accionista",
    "Otros nombres socio o accionista",
    "Razón social ",
    "Dirección",
    "Código dpto",
    "Código mcp",
    "País de Residencia o domicilio",
    "Valor patrimonial acciones o aportes al 31-12",
    "Porcentaje de participación",
    "Porcentaje de participación (posición decimal)"
  ],
  "1011": [
    "Concepto",
    "Saldos al 31-12"
  ],
  "1012": [
    "Concepto",
    "Tipo de documento",
    "NIT informado",
    "DV",
    "Primer apellido del informado",
    "Segundo apellido del informado",
    "Primer nombre del informado",
    "Otros nombres del informado",
    "Razón social informado",
    "País de Residencia o domicilio",
    "Valor al 31-12 "
  ],
  "1647": [
    "Concepto",
    "Tipo de documento de quien se recibe ingreso",
    "Número identificación de quien se recibe ingreso",
    "DV",
    "Primer apellido de quien se recibe ingreso",
    "Segundo apellido de quien se recibe ingreso",
    "Primer nombre de quien se recibe ingreso",
    "Otros nombres de quien se recibe ingreso",
    "Razón social de quien se recibe ingreso",
    "País de residencia o domicilio de quien se recibe ingreso",
    "Valor total de la operación",
    "Valor ingreso reintegrado transferido distribuido al tercero ",
    "Valor  Retención reintegrada   transferida distribuida al tercero ",
    "Tipo de documento del tercero para quien se recibió ingreso",
    "Identificación  del tercero para quien se recibió ingreso",
    "Primer apellido del tercero para quien se recibió ingreso",
    "Segundo apellido  del tercero para quien se recibió ingreso",
    "Primer nombre del tercero para quien se recibió ingreso",
    "Otros nombres del tercero para quien se recibió ingreso",
    "Razón social del tercero para quien se recibió ingreso",
    "Dirección",
    "Código dpto",
    "Código mcp",
    "País de residencia o domicilio"
  ],
  "2276": [
    "Entidad Informante",
    "Tipo de documento del beneficiario",
    "Número de Identificación del beneficiario",
    "Primer Apellido del beneficiario",
    "Segundo Apellido del beneficiario",
    "Primer Nombre del beneficiario",
    "Otros Nombres del beneficiario",
    "Dirección del beneficiario",
    "Departamento del beneficiario",
    "Municipio del beneficiario",
    "País del beneficiario ",
    "Pagos por Salarios (7601)",
    "Pagos por emolumentos eclesiásticos",
    "Pagos realizados con bonos electrónicos o de papel de servicio, cheques, tarjetas, vales, etc.",
    "Valor del exceso de los pagos por alimentación mayores a 41 UVT, art. 387-1 E.T.",
    "Pagos por honorarios",
    "Pagos por servicios",
    "Pagos por comisiones (7602)",
    "Pagos por prestaciones sociales (7603)",
    "Pagos por viáticos (7604)",
    "Pagos por gastos de representación (7605)",
    "Pagos por compensaciones trabajo asociado cooperativo",
    "Valor apoyos económicos no reembolsables o condonados, entregados por el Estado o financiados con recursos públicos, para financiar programas educativos.",
    "Otros pagos (7606)",
    "Cesantías e intereses de cesantías efectivamente pagadas al empleado",
    "Cesantías consignadas al fondo de cesantías",
    "Auxilio de cesantías reconocido a trabajadores del régimen tradicional del Código Sustantivo del Trabajo, Capítulo VII, Título VIII Parte Primera",
    "Pensiones de Jubilación, vejez o invalidez",
    "Total ingresos brutos por rentas de trabajo y pensión (suma de L-Z)",
    "Aportes obligatorios por salud a cargo del trabajador",
    "Aportes obligatorios a fondos de pensiones y solidaridad pensional a cargo del trabajador",
    "Aportes voluntarios al régimen de ahorro individual con solidaridad - RAIS",
    "Aportes voluntarios a fondos de pensiones voluntarias",
    "Aportes a cuentas AFC",
    "Aportes a cuentas AVC",
    "Valor de las retenciones en la fuente por pagos de rentas de trabajo o pensiones (7608)",
    "Impuesto sobre las ventas – IVA, mayor valor del costo o gasto",
    "Retención en la fuente a título de impuesto sobre las ventas – IVA.",
    "Pagos por alimentación hasta 41 UVT",
    "Valor ingreso laboral promedio de los últimos seis meses.",
    "Tipo de documento del dependiente económico",
    "Número de Identificación del dependiente económico",
    "Identificación del fideicomiso",
    "Tipo documento participante en contrato de colaboración",
    "Identificación participante en contrato colaboración"
  ]
};

export const EXOGENA_MAPPINGS: Record<string, Record<string, string[]>> = {
  "1001": {
    "5008": [
      "1504",
      "1504",
      "1506",
      "1506",
      "1508",
      "1508",
      "1512",
      "1512",
      "1516",
      "1516",
      "1520",
      "1520",
      "1524",
      "1524",
      "1528",
      "1528",
      "1532",
      "1536",
      "1540",
      "1540",
      "1544",
      "1544",
      "1548",
      "1548",
      "1552",
      "1552",
      "1556",
      "1560",
      "1562",
      "1564",
      "1564",
      "1568",
      "1568",
      "1572",
      "1572",
      "1576",
      "1576",
      "1580",
      "1580",
      "1584",
      "1584"
    ],
    "5002": [
      "236515",
      "5110",
      "5210",
      "7310"
    ],
    "5003": [
      "236520",
      "519505",
      "529505"
    ],
    "5004": [
      "236525",
      "5135",
      "5145",
      "5150",
      "5235",
      "5245",
      "5250",
      "7335",
      "7345",
      "7350",
      "7401"
    ],
    "5005": [
      "236530",
      "5120",
      "5220",
      "7320"
    ],
    "5007": [
      "236540",
      "6205",
      "71"
    ],
    "5055": [
      "510520",
      "510521",
      "520521",
      "520521",
      "720521",
      "720521"
    ],
    "5016": [
      "510563",
      "510566",
      "510581",
      "510584",
      "510595",
      "5125",
      "5130",
      "5140",
      "5155",
      "5195",
      "5225",
      "5230",
      "5240",
      "5255",
      "5295",
      "530505",
      "5315",
      "531505",
      "531510",
      "531515",
      "531520",
      "531595",
      "539520",
      "7325",
      "7330",
      "7340",
      "7355"
    ],
    "5011": [
      "510568",
      "510569"
    ],
    "5012": [
      "510570"
    ],
    "5010": [
      "510572",
      "510575",
      "510578"
    ],
    "5027": [
      "511035",
      "521035"
    ],
    "5015": [
      "5115",
      "511505",
      "511510",
      "511515",
      "511520",
      "511525",
      "511530",
      "511540",
      "511545",
      "511550",
      "511565",
      "511570",
      "511595",
      "5215",
      "7315"
    ],
    "5058": [
      "511535",
      "512505",
      "521535",
      "522505"
    ],
    "5023": [
      "513515",
      "523515"
    ],
    "5056": [
      "519520",
      "529520"
    ],
    "5006": [
      "5305"
    ],
    "5013": [
      "539525"
    ],
    "5014": [
      "539525"
    ],
    "5044": [
      "613570"
    ]
  },
  "1003": {
    "1303": [
      "135515",
      "13551510"
    ],
    "1302": [
      "13551505"
    ],
    "1304": [
      "13551515"
    ],
    "1305": [
      "13551520"
    ],
    "1306": [
      "13551525"
    ],
    "1307": [
      "13551530"
    ],
    "1308": [
      "13551535"
    ],
    "1301": [
      "13551540"
    ],
    "1310": [
      "13551545"
    ],
    "1311": [
      "13551550"
    ],
    "1312": [
      "13551555"
    ],
    "1313": [
      "13551560"
    ],
    "1309": [
      "135517"
    ],
    "1314": [
      "511510"
    ]
  },
  "1004": {},
  "1005": {
    "1005": [
      "240802"
    ],
    "1055": [
      "240804"
    ]
  },
  "1006": {
    "1006": [
      "240801"
    ],
    "1066": [
      "240803"
    ]
  },
  "1007": {
    "4001": [
      "41",
      "4105",
      "4110",
      "4115",
      "4120",
      "4125",
      "4130",
      "4135",
      "4140",
      "4145",
      "4150",
      "4155",
      "4160",
      "4165",
      "4170",
      "4175"
    ],
    "4002": [
      "42",
      "4205",
      "4210",
      "4215",
      "4220",
      "4225",
      "4230",
      "4235",
      "4240",
      "4245",
      "4248",
      "4250",
      "4255",
      "4260",
      "4275",
      "4295"
    ]
  },
  "1008": {
    "1315": [
      "1305"
    ],
    "1316": [
      "1310",
      "1315",
      "1320",
      "1325"
    ],
    "1317": [
      "1323",
      "1328",
      "1330",
      "1335",
      "1340",
      "1345",
      "1350",
      "1355",
      "1360",
      "1365",
      "1370",
      "1380",
      "1385"
    ],
    "1317R": [
      "135515",
      "13551505",
      "13551510",
      "13551515",
      "13551520",
      "13551525",
      "13551530",
      "13551535",
      "13551540",
      "13551545",
      "13551550",
      "13551555",
      "13551560",
      "135517"
    ],
    "1317M": [
      "135518"
    ],
    "1318": [
      "1390",
      "1399",
      "139905"
    ]
  },
  "1009": {
    "2208": [
      "2"
    ],
    "2203": [
      "2105",
      "2110",
      "2115",
      "2120",
      "2125",
      "2130",
      "2135",
      "2140",
      "2145",
      "2195"
    ],
    "2201": [
      "2205",
      "2210",
      "2215",
      "2220",
      "2225"
    ],
    "2206": [
      "2305",
      "2320",
      "2330",
      "2335",
      "2340",
      "2345",
      "2350",
      "2357",
      "2370",
      "2375",
      "2380",
      "2705",
      "2710",
      "2715",
      "2805",
      "2810",
      "2815",
      "2825",
      "2830",
      "2835",
      "2840",
      "2895"
    ],
    "2202": [
      "2310",
      "2315",
      "2355",
      "2360"
    ],
    "2206R": [
      "2365",
      "236505",
      "236510",
      "236515",
      "236520",
      "236525",
      "236530",
      "236535",
      "236540",
      "236545",
      "236550",
      "236555",
      "236560",
      "236565",
      "236570",
      "2367",
      "236701",
      "236702",
      "236703"
    ],
    "2206M": [
      "2368"
    ],
    "2204": [
      "2404",
      "2408",
      "2412",
      "2416",
      "2420",
      "2424",
      "2428",
      "2432",
      "2436",
      "2440",
      "2444",
      "2448",
      "2452",
      "2456",
      "2460",
      "2464",
      "2468",
      "2472",
      "2476",
      "2495"
    ],
    "2215": [
      "2505",
      "2515",
      "2520",
      "2525",
      "2530",
      "261010",
      "261020",
      "261015"
    ],
    "2214": [
      "2510",
      "261005"
    ],
    "2205": [
      "2530",
      "2532",
      "2535",
      "2540"
    ],
    "2207": [
      "2620"
    ],
    "2250": [
      "2820"
    ]
  },
  "1010": {
    "1010": [
      "3105",
      "3110",
      "3115",
      "3120",
      "3130",
      "3140"
    ]
  },
  "1011": {},
  "1012": {
    "1110": [
      "111005",
      "111505",
      "1120"
    ],
    "1115": [
      "111010",
      "111510"
    ],
    "1200": [
      "1215"
    ],
    "1201": [
      "1225"
    ],
    "1202": [
      "1235"
    ]
  },
  "1647": {
    "4070": [
      "2815"
    ]
  },
  "2276": {
    "7608": [
      "236505"
    ],
    "7603": [
      "2510",
      "2515",
      "2520",
      "2525",
      "2530",
      "261005",
      "261010",
      "261020",
      "261015",
      "2530"
    ],
    "7601": [
      "510503",
      "510506",
      "510512",
      "510515",
      "510524",
      "510527",
      "520503",
      "520506",
      "520512",
      "520515",
      "520524",
      "520527",
      "720503",
      "720506",
      "720512",
      "720515",
      "720524",
      "720527"
    ],
    "7602": [
      "510518",
      "519505",
      "520518",
      "529505",
      "720518"
    ],
    "7604": [
      "510520",
      "510521",
      "520521",
      "520521",
      "720521",
      "720521"
    ],
    "7606": [
      "510545",
      "520545",
      "510548",
      "520548",
      "510551",
      "510554",
      "510557",
      "520545",
      "520548",
      "520551",
      "520554",
      "520557",
      "720545",
      "720548",
      "720551",
      "720554",
      "720557"
    ],
    "7605": [
      "519520",
      "529520"
    ]
  }
};
